name: flutter_clg
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  webview_flutter: ^4.10.0 # Use the latest version from pub.dev
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.12


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
   